language: python

# addons:
#   postgresql: "9.3"

services:
  - mysql
  #- postgresql
  - sqlite3

env:
  global:
    #- PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    #- POSTGRES_USER=postgres
    - AIRFLOW_HOME=$HOME/airflow
    - AIRFLOW_CONFIG=$AIRFLOW_HOME/unittests.cfg
    - AIRFLOW_DB=$AIRFLOW_HOME/unittests.db

  matrix:
    - TOX_ENV=docs
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34

# sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmysqlclient-dev libpq-dev libffi-dev libssl-dev libsasl2-dev libkrb5-dev

install:
  - pip install --upgrade pip
  - pip install tox
  - pip install flake8


before_script:
  # Making sure airflow is installed
  - echo $AIRFLOW_DB
  - echo $AIRFLOW_HOME
  - echo $AIRFLOW_CONFIG
  - flake8 --ignore=F401,F403,E123,E129,E226,E712,F811 --max-line-length=110 --exclude=*init*.py airflow

script:
  - tox -e $TOX_ENV

branches:
  only:
    - master
    - /^(?i:travis)-.*$/
    - /^(?i:ci)-.*$/

notifications:
  email:
    - arthur.wiedmer+airflowtravis@gmail.com
