language: python

# addons:
#   postgresql: "9.3"

services:
  - mysql
  #- postgresql
  - sqlite3

env:
  global:
    #- PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    #- POSTGRES_USER=postgres
    - AIRFLOW_HOME=$HOME/airflow
    - AIRFLOW_CONFIG=$AIRFLOW_HOME/unittests.cfg
    - AIRFLOW_DB=$AIRFLOW_HOME/unittests.db

  matrix:
    - TOX_ENV=docs
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34

# sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmysqlclient-dev libpq-dev libffi-dev libssl-dev libsasl2-dev libkrb5-dev

install:
  - pip install --upgrade pip
  - pip install nose
  # - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
  - pip install tox
  - pip install flake8
  - pip install -r requirements.txt
  - pip install -q -e .[travis]


before_script:
  # Making sure airflow is installed
  - echo $AIRFLOW_DB
  - echo $AIRFLOW_HOME
  - echo $AIRFLOW_CONFIG
  - flake8 --ignore=F401,F403,E123,E129,E226,E712,F811 --max-line-length=110 --exclude=*init*.py airflow
  # - which airflow > /dev/null || python setup.py develop
  # initialize the db
  - if [[ $TOX_ENV =~ ^py.* ]]; then airflow initdb; fi
  # - ls -s $AIRFLOW_DB > /dev/null 2>&1 || airflow initdb
  # - ls -s $AIRFLOW_DB | egrep '^0 ' > /dev/null && airflow initdb
  # - psql -c 'create database airflow_db;' -U postgres
  # - mysql -e 'create database IF NOT EXISTS airflow_db;' -uroot || true

script:
  - tox -e $TOX_ENV

branches:
  only:
    - master
    - /^(?i:travis)-.*$/
    - /^(?i:ci)-.*$/

notifications:
  email:
    - arthur.wiedmer+airflowtravis@gmail.com
